apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: crypto-dashboard
spec:
  to:
    kind: Service
    name: crypto-dashboard
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
