name: BUILD  AND DEPLOY TO OPENSHIFT CLUSTER 

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: fastapi-app 
  REGISTRY: quay.io
  QUAY_ORG: ubiowororuki
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_TOKEN }}
  OPENSHIFT_NAMESPACE: ubiowororuki-dev
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/ -v --tb=short

  scan_docker:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ env.QUAY_PASSWORD }}

      - name: Scan Dockerfile with Trivy (Filesystem Scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL 

  build:
    name: Build, Scan and Push Image
    runs-on: ubuntu-latest
    needs: [test, scan_docker]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ env.QUAY_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build Docker image (load for Trivy)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          with:
          image-ref: quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL

      - name: Push image to Quay.io
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


  deploy:
    name: Deploy to OpenShift
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: 'latest'

      - name: Authenticate with OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true

      - name: Trigger Build via Webhook
        run: |
          curl -k -X POST -H "Authorization: Bearer ${{ secrets.OPENSHIFT_TOKEN }}" \
          -H "Content-Type: application/json" \
          ${{ secrets.OPENSHIFT_SERVER }}/apis/build.openshift.io/v1/namespaces/ubiowororuki-dev/buildconfigs/myapp-dev/webhooks/${{ secrets.WEBHOOK_SECRET }}/generic